import { LINES, DELIVERIES, PEOPLE, lineReady, type LineId, type QuestLine, type Delivery } from './story';
import { REGIONS, VILLAGE_NAMES } from './regions';
import type { Point } from './world';

export type JournalEntry={id:string;title:string;why:string;status:string;next:string;steps:string[];reward:string;done:boolean;available:boolean;point:Point|null;region:number;village:number|null};
export const QUEST_NOTES:Record<LineId,{why:string;offer:string;thanks:string}>={
 bell:{why:'Колокол возвращал людям имена. Некроманты заглушили его, и Брун хочет вернуть память погибших стражей.',offer:'Я помню имена тех, кто охранял эту дорогу. Некроманты украли голос нашего колокола. Разбей двух заклинателей и забери его язык у лунного алтаря. Когда падёт Госпожа тумана, колокол снова зазвучит. Я выкую тебе клинок, который лечит раны светом памяти.',thanks:'Слышишь? Колокол снова зовёт стражей по именам. Теперь их память защищает тебя. Клинок Рассвета возвращает 2 HP при попадании. Спасибо, что не прошёл мимо нашей беды.'},
 runes:{why:'Хранитель оставил письма дочери в трёх печатях. Лисандр ищет их, чтобы история семьи не исчезла в огне.',offer:'Караванщик спрятал письма своей дочери в трёх печатях Пепельного святилища. Читай их в порядке Луна, Искра, Корень: память, надежда, дом. Архонт не даст вынести письмо, пока жив. Верни его после победы - и я отдам посох хранителя, а не продам последнюю память о нём.',thanks:'В письме всего три слова: «Я вернусь домой». Для тебя они тоже важны. Посох трёх печатей выпускает три сгустка за один удар. Пусть эта чужая надежда поможет вернуть твою семью.'},
 wisp:{why:'Огонёк хранит голос пропавшего ученика Ивы. Его нужно вывести из пепла к восточному огню.',offer:'Мой ученик ушёл искать пленников и не вернулся. В святилище остался его огонёк. Найди его на западной тропе и держись рядом до восточного костра. Он пугается боли и замирает, если тебя ранят. Победи Архонта, чтобы огонь не погас. Я сохраню его голос в защитной печати для тебя.',thanks:'Он добрался до огня. Теперь я знаю, что его память не досталась дракону. Пепельная печать ослабляет магию на 18% и действует сразу. Ты вернул мне надежду - пусть она бережёт тебя.'},
};
export function lineJournal(q:QuestLine,bossDead:boolean):Omit<JournalEntry,'point'|'region'|'village'|'available'>{
 const d=LINES.find(d=>d.id===q.id)!,person=PEOPLE.find(p=>p.role===d.giver)!,ready=lineReady(q,bossDead),notes=QUEST_NOTES[q.id];
 const steps=q.id==='bell'?[`${q.kills>=2?'✓':'○'} Некроманты: ${q.kills}/2`,`${q.artifact?'✓':'○'} Язык колокола`]:q.id==='runes'?[`${q.runes>=1?'✓':'○'} Луна`,`${q.runes>=2?'✓':'○'} Искра`,`${q.runes>=3?'✓':'○'} Корень`]:[`${q.escorted?'✓':'○'} Проводить огонёк к восточному костру`];
 steps.push(`${bossDead?'✓':'○'} ${REGIONS[d.region].bossName}`);
 const next=q.claimed?'Обещание выполнено. Награда уже в вещах.':!q.accepted?`Поговори: ${person.name}, ${VILLAGE_NAMES[d.offered+1]}.`:ready?`Вернись к ${person.name} в посещённой деревне.`:q.id==='bell'&&q.kills<2?'Победи некромантов после принятия поручения.':q.id==='bell'&&!q.artifact?'Забери язык колокола у лунного алтаря (E).':q.id==='runes'&&q.runes<3?`Следующая печать: ${['Луна','Искра','Корень'][q.runes]} (E). Ошибка сбросит порядок.`:q.id==='wisp'&&!q.escorted?'Подойди к огоньку; веди его на восток, держась ближе 155 шагов.':`Победи хозяина: ${REGIONS[d.region].bossName}.`;
 return{id:`line:${q.id}`,title:d.name,why:notes.why,status:q.claimed?'Завершено':!q.accepted?'Ещё не принято':ready?'Готово к сдаче':'В дневнике',next,steps,reward:d.rewardName,done:q.claimed};
}
export function deliveryJournal(q:Delivery):Omit<JournalEntry,'point'|'region'|'village'|'available'>{
 const d=DELIVERIES.find(d=>d.id===q.id)!,giver=PEOPLE.find(p=>p.role===d.giver)!,receiver=PEOPLE.find(p=>p.role===d.receiver)!;
 return{id:`delivery:${q.id}`,title:d.name,why:d.description,status:q.claimed?'Завершено':q.delivered?'Посылка передана':q.accepted?'Посылка в сумке':`Откроется: ${d.seals} печатей`,next:q.claimed?'Люди получили помощь. Награда уже выдана.':!q.accepted?`Получить: ${giver.name}, ${VILLAGE_NAMES[d.from+1]}.`:q.delivered?`Награда: ${giver.name}, ${VILLAGE_NAMES[d.from+1]}.`:`Доставить: ${receiver.name}, ${VILLAGE_NAMES[d.to+1]} (E).`,steps:[`${q.accepted?'✓':'○'} Взять: ${d.parcel}`,`${q.delivered?'✓':'○'} Передать получателю`,`${q.claimed?'✓':'○'} Вернуться к заказчику`],reward:`${d.reward} ◈ и 1 искра мастерства`,done:q.claimed};
}
